const dictionaries: any = {
    en: {
        title: 'Welcome to my page',
        description: 'This is a simple page that can be translated into Spanish, English and French.',
        home: 'Home',
        generation: 'Generation',
        gen1: 'Generation 1',
        gen2: 'Generation 2',
        gen3: 'Generation 3',
        gen4: 'Generation 4',
        gen5: 'Generation 5',
        gen6: 'Generation 6',
        gen7: 'Generation 7',
        gen8: 'Generation 8',
        gen9: 'Generation 9',
        contact: 'Contact',
        bannerAlt: 'Main banner',
        viewDetail: 'View details',
        loading: 'Loading...',
        notFound: 'Generation not found',
        stats: 'Base Stats',
        close: 'Close',
        message: 'This website is generated in NEXT by the student Cristian from IES Cura Valera.',
        errorTitle: 'Something went wrong',
        errorButton: 'Try again',
        notFoundTitle: '404 - Page Not Found',
        backToHome: 'Back to Home',
        next: 'Next',
        previous: 'Previous',
    },
    es: {
        title: 'Bienvenido a mi página',
        description: 'Esta es una página sencilla que se puede traducir al español, inglés y francés.',
        home: 'Inicio',
        generation: 'Generación',
        gen1: 'Generación 1',
        gen2: 'Generación 2',
        gen3: 'Generación 3',
        gen4: 'Generación 4',
        gen5: 'Generación 5',
        gen6: 'Generación 6',
        gen7: 'Generación 7',
        gen8: 'Generación 8',
        gen9: 'Generación 9',
        contact: 'Contacto',
        bannerAlt: 'Banner principal',
        viewDetail: 'Ver detalle',
        loading: 'Cargando...',
        notFound: 'Generación no encontrada',
        stats: 'Estadísticas',
        close: 'Cerrar',
        message: 'Esta web está generada en NEXT por el alumno Cristian del IES Cura Valera.',
        errorTitle: 'Algo salió mal',
        errorButton: 'Reintentar',
        notFoundTitle: '404 - Página no encontrada',
        backToHome: 'Volver al Inicio',
        next: 'Siguiente',
        previous: 'Anterior',
    },
    fr: {
        title: 'Bienvenue sur ma page',
        description: 'Cette est une page simple qui peut être traduite en français, anglais et espagnol.',
        home: 'Accueil',
        generation: 'Génération',
        gen1: 'Génération 1',
        gen2: 'Génération 2',
        gen3: 'Génération 3',
        gen4: 'Génératión 4',
        gen5: 'Génératión 5',
        gen6: 'Génératión 6',
        gen7: 'Génératión 7',
        gen8: 'Génératión 8',
        gen9: 'Génératión 9',
        contact: 'Contact',
        bannerAlt: 'Bannière principale',
        viewDetail: 'Voir le détail',
        loading: 'Chargement...',
        notFound: 'Génération non trouvée',
        stats: 'Statistiques',
        close: 'Fermer',
        message: 'Ce site web est généré en NEXT par l\'étudiant Cristian de l\'IES Cura Valera.',
        errorTitle: 'Quelque chose s\'est mal passé',
        errorButton: 'Réessayer',
        notFoundTitle: '404 - Page non trouvée',
        backToHome: 'Retour à l\'accueil',
        next: 'Suivant',
        previous: 'Précédent',
    }
};

export const getDictionary = (lang: string) => dictionaries[lang] || dictionaries.en;